/**
 * Nomes em português dos campos da API do ZSGO (que vêm em inglês). Campos
 * que não estejam aqui aparecem com o nome original tornado legível.
 */
const ROTULOS: Record<string, string> = {
  identity: "Identificação",
  address: "Morada",
  billing: "Faturação",
  settings: "Contactos e definições",
  document: "Documento",
  customer: "Cliente",
  supplier: "Fornecedor",
  items: "Linhas",
  allocations: "Documentos a liquidar",
  transport: "Transporte",
  load: "Carga",
  delivery: "Descarga",
  email: "Enviar por email",
  code: "Código",
  name: "Nome",
  description: "Descrição",
  tax_id: "NIF",
  tax_subject: "Sujeito passivo",
  country_code: "País",
  postal_code: "Código postal",
  city: "Localidade",
  region_code: "Região fiscal",
  payment_option_id: "Condição de pagamento",
  payment_method_id: "Método de pagamento",
  exemption_code: "Motivo de isenção",
  exemption_detail: "Detalhe da isenção",
  salesman_code: "Vendedor",
  price_line: "Linha de preço",
  global_discount: "Desconto global (%)",
  retention: "Retenção na fonte",
  retention_rate: "Taxa de retenção (%)",
  phone: "Telefone",
  mobile: "Telemóvel",
  website: "Website",
  fax: "Fax",
  notes: "Notas",
  inactive: "Inativo",
  in_litigation: "Em contencioso",
  blocked: "Bloqueado",
  print_type: "Modo de envio",
  commitment_number: "Nº de compromisso (B2G)",
  requesting_service: "Serviço requisitante (B2G)",
  type: "Tipo",
  series: "Série",
  issue_date: "Data de emissão",
  due_date: "Data de vencimento",
  auto_confirm: "Finalizar logo",
  warehouse_id: "Armazém",
  reference: "Referência",
  tax_included: "Preços com IVA",
  currency: "Moeda",
  without_values: "Sem valores",
  product_reference: "Artigo",
  quantity: "Quantidade",
  unit_price_net: "Preço unitário",
  unit_price: "Preço unitário",
  discount: "Desconto (%)",
  origin_id: "Documento de origem",
  origin_line_id: "Linha de origem",
  vehicle_registration: "Matrícula",
  document_type: "Tipo de documento",
  document_id: "Documento",
  amount: "Valor",
  parent_id: "Família-mãe",
  active: "Ativo",
  family_id: "Família",
  unit_code: "Unidade",
  tax_rate: "Taxa de IVA",
  sale_tax: "IVA de venda",
  purchase_tax: "IVA de compra",
  item_type_code: "Tipo de artigo",
  barcode: "Código de barras",
  price: "Preço",
  prices: "Preços",
  cost: "Custo",
  stock: "Stock",
  reason: "Motivo",
  export_type: "Tipo de exportação",
  year: "Ano",
  month: "Mês",
  start_date: "Data inicial",
  end_date: "Data final",
  date_from: "De",
  date_to: "Até",
  search: "Procurar",
  status: "Estado",
  group: "Grupo",
  document_status: "Estado do documento",
  movementType: "Tipo de movimento",
  supplier_code: "Fornecedor",
  customer_code: "Cliente",
  to: "Para",
  cc: "Cc",
  subject: "Assunto",
  body: "Mensagem",
  message: "Mensagem",
  frequency: "Periodicidade",
  interval: "Intervalo",
  start: "Início",
  end: "Fim",
  next_date: "Próxima data",
  abbreviation: "Abreviatura",
  symbol: "Símbolo",
  days: "Dias",
  pdf: "PDF",
  id: "Id",
  number: "Número",
  pending: "Por pagar",
  pending_amount: "Por pagar",
  total: "Total",
  net_total: "Líquido",
  tax_total: "IVA",
  net: "Líquido",
  tax: "IVA",
  totals: "Totais",
  pdf_url: "PDF",
  date: "Data",
  base: "Base",
  rate: "Taxa (%)",
  commission: "Comissão (%)",
  salesman: "Vendedor",
  annul_reason: "Motivo da anulação",
  created_at: "Criado em",
  updated_at: "Alterado em",
  processId: "Pedido",
  label: "Documento",
  acronym: "Sigla",
};

export function rotulo(chave: string): string {
  if (ROTULOS[chave]) return ROTULOS[chave];
  const t = chave.replace(/_/g, " ").replace(/([a-z])([A-Z])/g, "$1 $2");
  return t.charAt(0).toUpperCase() + t.slice(1);
}
